name: secrets and env's pipeline

on: 
  schedule:
    - cron: '0 0 * * *'

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  NODE_ENV: production


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print Environment Variables
        run: |
          echo "MY_SECRET: $MY_SECRET
          echo "NODE_ENV: $NODE_ENV"
          echo "API_URL: ${{ variables.API_URL }}"
  
      - name: Run shell command
        run: |
          echo "Run successful!!" 